### ISSUE TITLE
Server-Time difference.

### ISSUE THREAD

**Issue by Evanskiragu** [bnjunge/MPESA-API-Tutorial#1]
I hosted the stkPush, but it will not work, unless you have this: 

 date_default_timezone_set('Africa/Nairobi');

Right before getting the TimeStamp. 
This is notorious when working with offshore servers that are a day behind.

**Comment by bnjunge** [comment]
Fixed, Thanks for pointing out.

**Comment by Daenjel** [comment]
my code is returning my access_token key. any help please?
