### ISSUE TITLE
Mpesa API Error

### ISSUE THREAD

**Issue by thomasabol608** [bnjunge/MPESA-API-Tutorial#3]
{"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SCO-AddURLVault failed. Reason: ResponseCode 409 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}

**Comment by StilinskiCyril** [comment]
You must have defined your Shortcode which is Lipa na Mpesa Online Shortcode. From Safaricom, “the Lipa na Mpesa Online Shortcode is meant for STK push only.” And that is why you are unable to register yourconfirmation and validation URL.

**Comment by smartjef** [comment]
If you're experiencing unexplained failures when sending payloads to Safaricom, double-check for special characters in any of the fields, especially ones like TransactionDesc, AccountReference, or Remarks.

In our case, we noticed that certain special characters (e.g., @, #, &, etc.) used in values coming from clients (like titles or descriptions) were causing requests to silently fail or return errors from MPESA.

💡 Recommendation:
Always sanitize or validate input fields before sending them in the payload — even if it comes from a client or dynamic source.
