### ISSUE TITLE
Execution of ServiceCallout SCO-AddURLVault failed

### ISSUE THREAD

**Issue by PatrickNthiwa** [bnjunge/MPESA-API-Tutorial#7]
ZnQC0gxUxpLzh2SLAsX0G5UCydmB{"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SC-SearchURL failed. Reason: ResponseCode 503 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}{"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SC-SearchURL failed. Reason: ResponseCode 503 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}

**Comment by PatrickNthiwa** [comment]
i have following your tutorials and i have happened to have this error ,kindly can you help?

**Comment by ndegwairungu** [comment]
Have you successfully initiated an stk push? I have an updated send stk code.

**Comment by PatrickNthiwa** [comment]
Hi, i  was doing a C2B integration  without initiating an stk push.
I have not succeded yet!

**Comment by PatrickNthiwa** [comment]
This is the error message am getting

{"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution
of ServiceCallout SC-SearchURL failed. Reason: ResponseCode 503 is treated
as
error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}

**Comment by PatrickNthiwa** [comment]
Hi,
Did you find  a way the error  could be solved?

**Comment by PatrickNthiwa** [comment]
Error was successfully solved
i changes the shortcode to 600988 then i re-registered my urls

**Comment by PatrickNthiwa** [comment]
HI
